version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:
### Form.io ##############################################
  formio:
    build: ./Formio
    env_file:
      - ./.env
    ports:
      - '${FORMIO_PORT}:3001'
    restart: unless-stopped
    networks:
      - backend
    depends_on:
    - mongo
### MongoDB ##############################################
  mongo:
    build: ./MongoDB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}"
      - "MONGO_INITDB_DATABASE=${MONGO_DB_NAME}"
      - "MONGO_DB_USER=${MONGO_DB_USER}"
      - "MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}"
    networks:
      - backend
    restart: unless-stopped
### OpenCpu #############################################
  opencpu:
    build: ./OpenCpu
    ports:
      - "${OPENCPU_PORT_HTTPS}:443"
      - "${OPENCPU_PORT_HTTP}:80"
    networks:
      - backend
    restart: unless-stopped
### Portainer ################################################
  portainer:
    build:
      context: ./Portainer
    volumes:
      - ${DATA_PATH_HOST}/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9010:9000
### NetData ################################################
  netdata:
    image: titpetric/netdata:latest
    cap_add:
    - SYS_PTRACE
    volumes:
    - /:/host:ro
    ports:
      - "${NETDATA_PORT}:19999"
    networks:
      - backend
    