version: '3'

services:
  formio-api:
    image: unfao/formio-api
    build: .
    env_file:
      - ./.env
    ports:
      - '${API_PORT}:443'
    restart: unless-stopped

networks:
  default:
    external:
      name: '${NETWORK}'
    