version: '3'
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
  kong-net:
    driver: ${NETWORKS_DRIVER}

volumes:
  mongo:
    driver: ${VOLUMES_DRIVER}

services:
### Workspace #############################################
  workspace:
    build:
      context: ./Workspace
    ports:
      - "${PORTAINER_PORT}:9000"
    networks:
      - backend
      - frontend
    environment:
      - "API_URL=http://ironfunctions:8080"
      - "JWT_AUTH_KEY=${IRONFUNCTIONS_JWT}"
    restart: unless-stopped
### Rundeck #############################################
  rundeck:
    build:
      context: ./Rundeck
    environment:
      - "EXTERNAL_SERVER_URL=${RUNDECK_EXTERNAL_SERVER_URL}"
    ports:
      - '${RUNDECK_PORT_HTTP}:4440'
    networks:
      - backend
### Rundeck-cli #############################################
  rundeck-cli:
    build:
      context: ./Rundeck/rundeck-cli
    environment:
      - "RD_URL=${RUNDECK_CLI_RD_URL}"
      - "RD_AUTH_PROMPT=${RUNDECK_CLI_RD_AUTH_PROMPT}"
      - "RD_USER=${RUNDECK_CLI_RD_USER}"
      - "RD_PASSWORD=${RUNDECK_CLI_RD_PASSWORD}"
    networks:
      - backend
### Cordova #############################################
  cordova:
    build:
      context: ./Cordova
    volumes:
      - ${DATA_PATH_HOST}/cordova/app:/tmp/app
### Form.io ##############################################
  formio:
    build: ./Formio
    env_file:
      - ./.env
    ports:
      - '${FORMIO_PORT}:3001'
    restart: unless-stopped
    networks:
      - backend
    depends_on:
    - mongo
    restart: unless-stopped
### MongoDB ##############################################
  mongo:
    build: ./MongoDB
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}"
      - "MONGO_INITDB_DATABASE=${MONGO_DB_NAME}"
      - "MONGO_DB_USER=${MONGO_DB_USER}"
      - "MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}"
    networks:
      - backend
    restart: unless-stopped
### MongoDB EXPORTER #######################################
  mongo_exporter:
    build: ./MongoDB/exporter
    ports:
      - "9104:9104"
    environment:
      - "MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017"
    networks:
      - backend
    depends_on:
      - mongo
    command: "dockerize -wait http://api:80"
    restart: unless-stopped
### OpenCpu #############################################
  opencpu:
    build: ./OpenCpu
    ports:
      - "${OPENCPU_PORT_HTTPS}:443"
      - "${OPENCPU_PORT_HTTP}:80"
    networks:
      - backend
    restart: unless-stopped
### KONG DATABASE ################################################
  kong-database:
    build:
      context: ./Kong/database
    volumes:
      - ${DATA_PATH_HOST}/Postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      - backend
      - kong-net
    environment:
      - "POSTGRES_PASSWORD=kongpassword"
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
    restart: unless-stopped
### KONG DATABASE EXPORTER ################################################
  kong-database_exporter:
    build:
      context: ./Kong/database/exporter
    environment:
      - "DATA_SOURCE_NAME=postgresql://kong:kong@kong-database:5432/?sslmode=disable"
    ports: 
      - "9187:9187"
    restart: unless-stopped
### KONG MIGRATIONS ################################################
  kong-migrations:
    build:
      context: ./Kong
    networks:
      - backend
      - kong-net
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_PASSWORD=kongpassword"
      - "KONG_PG_HOST=kong-database"
      - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
    command: kong migrations up
    depends_on:
      - kong-database
### KONG SERVICE ################################################
  kong:
    build:
      context: ./Kong
    networks:
      - backend
      - kong-net
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_PASSWORD=kongpassword"
      - "KONG_PG_HOST=kong-database"
      - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-database
    restart: unless-stopped
### KONGA UI ################################################
  konga:
    build:
      context: ./Kong/ui
    ports:
      - "1337:1337"
    networks:
      - backend
      - kong-net
    restart: unless-stopped
### IronFunctions ########################################
  ironfunctions:
    build:
      context: ./IronFunctions
    volumes:
      - ${DATA_PATH_HOST}/ironFunctions_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${IRONFUNCTIONS_PORT}:8080"
    networks:
      - backend
    environment:
      - "SERVICE_PORTS=${IRONFUNCTIONS_PORT}"
    restart: unless-stopped
### IronFunctions UI ########################################
  ironfunctionsui:
    build:
      context: ./IronFunctions/Ui
    ports:
      - "${IRONFUNCTIONS_UI_PORT}:4000"
    networks:
      - backend
    environment:
      - "API_URL=http://ironfunctions:8080"
    restart: unless-stopped
    depends_on:
      - ironfunctions
### Portainer ################################################
  portainer:
    build:
      context: ./Portainer
    volumes:
      - ${DATA_PATH_HOST}/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORTAINER_PORT}:9000"
    restart: unless-stopped
### NetData ################################################
  netdata:
    image: titpetric/netdata:latest
    cap_add:
    - SYS_PTRACE
    volumes:
    - /:/host:ro
    ports:
      - "${NETDATA_PORT}:19999"
    networks:
      - backend
    restart: unless-stopped
### Prometheus ################################################
  prometheus:
    build:
      context: ./Prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
    restart: unless-stopped
### Grafana ################################################
  grafana:
    build:
      context: ./Grafana
    ports:
      - "3010:3000"
    networks:
      - backend 
    volumes:
      - ${DATA_PATH_HOST}/grafana:/var/lib/grafana
    restart: unless-stopped
### Mailhog #########################################
  mailhog:
    build: ./Mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend 
    restart: unless-stopped